import type { Team, Player, Game, Tournament, TournamentStanding } from "./types"

export const mockTeams: Team[] = [
  {
    id: "1",
    name: "Lakers",
    logo: "/lakers-basketball-team-logo.png",
    primaryColor: "#552583",
    secondaryColor: "#FDB927",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Warriors",
    logo: "/warriors-basketball-team-logo.png",
    primaryColor: "#1D428A",
    secondaryColor: "#FFC72C",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    name: "Bulls",
    logo: "/bulls-basketball-team-logo.png",
    primaryColor: "#CE1141",
    secondaryColor: "#000000",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "4",
    name: "Celtics",
    logo: "/celtics-basketball-team-logo.png",
    primaryColor: "#007A33",
    secondaryColor: "#BA9653",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockPlayers: Player[] = [
  // Lakers players
  {
    id: "1",
    teamId: "1",
    name: "LeBron James",
    number: 23,
    position: "SF",
    height: "6'9\"",
    weight: "250 lbs",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    teamId: "1",
    name: "Anthony Davis",
    number: 3,
    position: "PF",
    height: "6'10\"",
    weight: "253 lbs",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  // Warriors players
  {
    id: "3",
    teamId: "2",
    name: "Stephen Curry",
    number: 30,
    position: "PG",
    height: "6'2\"",
    weight: "185 lbs",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "4",
    teamId: "2",
    name: "Klay Thompson",
    number: 11,
    position: "SG",
    height: "6'6\"",
    weight: "215 lbs",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockTournaments: Tournament[] = [
  {
    id: "1",
    name: "Copa de Verano 2024",
    description: "Torneo de básquet de verano con los mejores equipos de la región",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    status: "active",
    format: "single-elimination",
    maxTeams: 8,
    registeredTeams: ["1", "2", "3", "4"],
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "2",
    name: "Liga Primavera 2025",
    description: "Liga regular con formato de todos contra todos",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-05-31"),
    status: "upcoming",
    format: "round-robin",
    maxTeams: 6,
    registeredTeams: ["1", "2"],
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-11-15"),
  },
]

export const mockGames: Game[] = [
  {
    id: "1",
    tournamentId: "1",
    homeTeamId: "1",
    awayTeamId: "2",
    scheduledDate: new Date("2024-12-15T19:00:00"),
    status: "scheduled",
    homeScore: 0,
    awayScore: 0,
    quarter: 1,
    timeRemaining: "10:00",
    round: "semifinals",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    tournamentId: "1",
    homeTeamId: "3",
    awayTeamId: "4",
    scheduledDate: new Date("2024-12-16T20:00:00"),
    status: "scheduled",
    homeScore: 0,
    awayScore: 0,
    quarter: 1,
    timeRemaining: "10:00",
    round: "semifinals",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockTournamentStandings: TournamentStanding[] = [
  {
    tournamentId: "1",
    teamId: "1",
    wins: 2,
    losses: 0,
    pointsFor: 210,
    pointsAgainst: 180,
    pointsDifferential: 30,
    gamesPlayed: 2,
  },
  {
    tournamentId: "1",
    teamId: "2",
    wins: 1,
    losses: 1,
    pointsFor: 195,
    pointsAgainst: 200,
    pointsDifferential: -5,
    gamesPlayed: 2,
  },
  {
    tournamentId: "1",
    teamId: "3",
    wins: 1,
    losses: 1,
    pointsFor: 188,
    pointsAgainst: 192,
    pointsDifferential: -4,
    gamesPlayed: 2,
  },
  {
    tournamentId: "1",
    teamId: "4",
    wins: 0,
    losses: 2,
    pointsFor: 175,
    pointsAgainst: 196,
    pointsDifferential: -21,
    gamesPlayed: 2,
  },
]
